### ISSUE TITLE
运行任何命令都报错:panic: runtime error: index out of range [1] with length 0

### ISSUE THREAD

**Issue by theLSA** [tickstep/cloudpan189-go#103]
前两天还正常，今天就出现如下报错，是否天翼云的登录接口变了？
//比如./cloudpan189-go help或者./cloudpan189-go sign
```

panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
github.com/tickstep/cloudpan189-api/cloudpan.getLoginParams(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/tickstep/cloudpan189-api@v0.1.0/cloudpan/login.go:151 +0x4b2
github.com/tickstep/cloudpan189-api/cloudpan.Login(0xc00028ebf8, 0x6, 0xc00028ec60, 0xa, 0xc00034a5a0, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/tickstep/cloudpan189-api@v0.1.0/cloudpan/login.go:68 +0xc5
github.com/tickstep/cloudpan189-go/cmder.DoLoginHelper(0xc00028ebf8, 0x6, 0xc00028ec60, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/cmder/cmder_helper.go:81 +0x2f1
github.com/tickstep/cloudpan189-go/cmder.TryLogin(0xc0001701c0)
	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/cmder/cmder_helper.go:122 +0x125
main.checkLoginExpiredAndRelogin()
	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/main.go:77 +0x5a
main.main()
	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/main.go:86 +0x86
```

**Comment by duchenpaul** [comment]
一样, 删除`cloud189_config.json`重新登陆显示登录失败.
估计是网页改了

```
cloudpan189-go > login
请输入用户名(手机号/邮箱/别名), 回车键提交 > 189********
请输入密码(输入的密码无回显, 确认输入完成, 回车提交即可) > 
APP登录失败： 登录失败
登录失败
```

**Comment by mou-min** [comment]
也一样，以为IP被强了，结果几台服务器都一样返回信息。

**Comment by yww211** [comment]
+1
![image](https://github.com/user-attachments/assets/5832a833-b3d7-447a-9340-f204d2457640)

**Comment by yww211** [comment]
@tickstep help~

**Comment by immoke** [comment]
今天刚刚下载这个项目，结果一直报相同的错。我一度怀疑自己账号密码错了

**Comment by equator8848** [comment]
应该是无了，天翼云可能想推自己的API，就改版了。https://cloud.189.cn/web/open#/abilityIntro/api

**Comment by MaurUppi** [comment]
https://github.com/MaurUppi/cloudpan189-go

可以看看这个，我 forked 并修复可以用了。 

@immoke @equator8848 @yww211
