### ISSUE TITLE
无法登陆， 登录时报错

### ISSUE THREAD

**Issue by guanzhilian** [tickstep/cloudpan189-go#104]
panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
github.com/tickstep/cloudpan189-api/cloudpan.getLoginParams(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/tickstep/cloudpan189-api@v0.1.0/cloudpan/login.go:151 +0x4b2
github.com/tickstep/cloudpan189-api/cloudpan.Login(0xc000330440, 0xb, 0xc000022340, 0xc, 0xc000070120, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/tickstep/cloudpan189-api@v0.1.0/cloudpan/login.go:68 +0xc5
github.com/tickstep/cloudpan189-go/cmder.DoLoginHelper(0xc000330440, 0xb, 0xc000022340, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/cmder/cmder_helper.go:81 +0x2f1
github.com/tickstep/cloudpan189-go/internal/command.RunLogin(0x0, 0x0, 0x0, 0x0, 0x0, 0xc0002a9050, 0x40a43f, 0xc0002a9050, 0x7b5956, 0xc000070090, ...)
	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/internal/command/login.go:132 +0xcb
github.com/tickstep/cloudpan189-go/internal/command.CmdLogin.func1(0xc00007e160, 0xce9940, 0xc00007c2a0)
	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/internal/command/login.go:50 +0x17b
github.com/urfave/cli.HandleAction(0x8e1cc0, 0x9af560, 0xc00007e160, 0xc00007e160, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0x105
github.com/urfave/cli.Command.Run(0x984747, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x991411, 0x18, 0x0, ...)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x579
github.com/urfave/cli.(*App).Run(0xc000192380, 0xc0003238c0, 0x2, 0x2, 0x0, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x7e8
main.main.func1(0xc0000ecdc0)
	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/main.go:356 +0x78b
github.com/urfave/cli.HandleAction(0x8d9420, 0xc00032ec60, 0xc0000ecdc0, 0xc0000ecdc0, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:525 +0x59
github.com/urfave/cli.(*App).Run(0xc000192380, 0xc00008c1f0, 0x1, 0x1, 0x0, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:285 +0x655
main.main()
	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/main.go:547 +0x15e7

**Comment by Antidington** [comment]
Same issue

**Comment by cly2625** [comment]
+1

**Comment by wdisk2020** [comment]
+1

**Comment by LiuYuLu** [comment]
+1

**Comment by MaurUppi** [comment]
https://github.com/MaurUppi/cloudpan189-go
