### ISSUE TITLE
报错登录不了 

### ISSUE THREAD

**Issue by Qkehan** [tickstep/cloudpan189-go#105]
系统 wsl fedora  目录 /home/user/  

报错登录不了  看不懂

panic: runtime error: index out of range [1] with length 0
goroutine 1 [running]:
github.com/tickstep/cloudpan189-api/cloudpan.getLoginParams(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/tickstep/cloudpan189-api@v0.1.0/cloudpan/login.go:151 +0x4b2
github.com/tickstep/cloudpan189-api/cloudpan.Login(0xc00012c00a, 0xb, 0xc00012c02a, 0xc, 0xc00007c090, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/tickstep/cloudpan189-api@v0.1.0/cloudpan/login.go:68 +0xc5
github.com/tickstep/cloudpan189-go/cmder.DoLoginHelper(0xc00012c00a, 0xb, 0xc00012c02a, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/cmder/cmder_helper.go:81 +0x2f1
github.com/tickstep/cloudpan189-go/internal/command.RunLogin(0xc00012c00a, 0xb, 0xc00012c02a, 0xc, 0xc, 0xc00032d050, 0x40a43f, 0xc00032d050, 0x7b5956, 0xc00007c000, ...)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/internal/command/login.go:132 +0xcb
github.com/tickstep/cloudpan189-go/internal/command.CmdLogin.func1(0xc000078160, 0xce9940, 0xc0000722a0)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/internal/command/login.go:50 +0x17b
github.com/urfave/cli.HandleAction(0x8e1cc0, 0x9af560, 0xc000078160, 0xc000078160, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0x105
github.com/urfave/cli.Command.Run(0x984747, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x991411, 0x18, 0x0, ...)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x579
github.com/urfave/cli.(*App).Run(0xc0000b2540, 0xc000122080, 0x4, 0x4, 0x0, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x7e8
main.main.func1(0xc0000f6dc0)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/main.go:356 +0x78b
github.com/urfave/cli.HandleAction(0x8d9420, 0xc0003b0c60, 0xc0000f6dc0, 0xc0000f6dc0, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:525 +0x59
github.com/urfave/cli.(*App).Run(0xc0000b2540, 0xc00009e1f0, 0x1, 0x1, 0x0, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:285 +0x655
main.main()
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/main.go:547 +0x15e7

**Comment by MaurUppi** [comment]
https://github.com/MaurUppi/cloudpan189-go
