### ISSUE TITLE
centos 7.x 频繁报如下错误

### ISSUE THREAD

**Issue by maokey** [tickstep/cloudpan189-go#55]
![image](https://user-images.githubusercontent.com/19211035/137272320-bdc34df4-c2b7-4964-9993-b9ffe6ae381a.png)

**Comment by tickstep** [comment]
应该是登陆接口改了

**Comment by salvation-z** [comment]
遇到相同的错误了，版本0.1.1，ubuntu使用正常，centos下没办法下载

**Comment by salvation-z** [comment]
遇到相同的错误，登录的时候会报错，版本是0.1.1
```
goroutine 1 [running]:
github.com/tickstep/cloudpan189-api/cloudpan.getLoginParams(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/tickstep/cloudpan189-api@v0.0.8/cloudpan/login.go:151 +0x4b2
github.com/tickstep/cloudpan189-api/cloudpan.Login(0xc000410040, 0xb, 0xc00037a2b0, 0xb, 0xc0001dc3f0, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/tickstep/cloudpan189-api@v0.0.8/cloudpan/login.go:68 +0xc5
github.com/tickstep/cloudpan189-go/cmder.DoLoginHelper(0xc000410040, 0xb, 0xc00037a2b0, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/cmder/cmder_helper.go:81 +0x2f1
github.com/tickstep/cloudpan189-go/internal/command.RunLogin(0x0, 0x0, 0x0, 0x0, 0x0, 0xc0002f7448, 0x40a43f, 0xc0002f7448, 0x7a9076, 0xc0001dc2d0, ...)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/internal/command/login.go:132 +0xcb
github.com/tickstep/cloudpan189-go/internal/command.CmdLogin.func1(0xc000146dc0, 0xcd3840, 0xc000362760)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/internal/command/login.go:50 +0x17b
github.com/urfave/cli.HandleAction(0x8d4ba0, 0x9a0178, 0xc000146dc0, 0xc000146dc0, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0x105
github.com/urfave/cli.Command.Run(0x975242, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x981f23, 0x18, 0x0, ...)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x579
github.com/urfave/cli.(*App).Run(0xc0001de380, 0xc00001e040, 0x2, 0x2, 0x0, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x7e8
main.main()
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/main.go:477 +0x18ba
```
