### ISSUE TITLE
登陆失败，无限报异常

### ISSUE THREAD

**Issue by kugooer** [tickstep/cloudpan189-go#70]
[2022-9-9 14:50:29.881] response: {"expiresIn":1665348629000,"accessToken":"E9B23B7xxxxxxxxxxxxxxxxx80746"}

[2022-9-9 14:50:29.881] do request url: https://cloud.189.cn/ssoLogin.action?sessionKey=6b169da9-0c98-40c8-ad8f-7dfe5c181baa&redirectUrl=main.action%23recycle
[2022-9-9 14:50:30.198] get COOKIE_LOGIN_USER by session key
[2022-9-9 14:50:30.395] get user info failed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x12c pc=0x83ed01a]

goroutine 1 [running]:
github.com/tickstep/cloudpan189-go/internal/command.CmdLogin.func1(0x94f8580, 0x0, 0x87bc0a0)
	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/internal/command/login.go:61 +0x2ba
github.com/urfave/cli.HandleAction(0x843da40, 0x84e45c0, 0x94f8580, 0x94f8580, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0xd0
github.com/urfave/cli.Command.Run(0x84b9a92, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x84c67e5, 0x18, 0x0, ...)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x48f
github.com/urfave/cli.(*App).Run(0x95f1180, 0x966e240, 0x4, 0x4, 0x0, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x673
main.main.func1(0x94f8420)
	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/main.go:309 +0x681
github.com/urfave/cli.HandleAction(0x8437780, 0x965ca60, 0x94f8420, 0x94f8420, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:525 +0x48
github.com/urfave/cli.(*App).Run(0x95f1180, 0x948c110, 0x1, 0x1, 0x0, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:285 +0x560
main.main()
	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/main.go:477 +0xf97

**Comment by tickstep** [comment]
新版本应该解决这个问题了

**Comment by kgggggb** [comment]
> 新版本应该解决这个问题了

`root@Ubuntu:/home/Ubuntu/189# ./cloudpan189-go 
提示: 方向键上下可切换历史命令.
提示: Ctrl + A / E 跳转命令 首 / 尾.
提示: 输入 help 获取帮助.
cloudpan189-go > login
请输入用户名(手机号/邮箱/别名), 回车键提交 > ***
请输入密码(输入的密码无回显, 确认输入完成, 回车提交即可) > 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x12c pc=0x83ed01a]

goroutine 1 [running]:
github.com/tickstep/cloudpan189-go/internal/command.CmdLogin.func1(0x9722420, 0x0, 0x87bc0a0)
	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/internal/command/login.go:61 +0x2ba
github.com/urfave/cli.HandleAction(0x843da40, 0x84e45c0, 0x9722420, 0x9722420, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0xd0
github.com/urfave/cli.Command.Run(0x84b9a92, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x84c67e5, 0x18, 0x0, ...)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x48f
github.com/urfave/cli.(*App).Run(0x95f9340, 0x97140c0, 0x2, 0x2, 0x0, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x673
main.main.func1(0x9504420)
	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/main.go:309 +0x681
github.com/urfave/cli.HandleAction(0x8437780, 0x966aa60, 0x9504420, 0x9504420, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:525 +0x48
github.com/urfave/cli.(*App).Run(0x95f9340, 0x949e110, 0x1, 0x1, 0x0, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:285 +0x560
main.main()
	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/main.go:477 +0xf97
root@Ubuntu:/home/Ubuntu/189# ./cloudpan189-go 
提示: 方向键上下可切换历史命令.
提示: Ctrl + A / E 跳转命令 首 / 尾.
提示: 输入 help 获取帮助.
cloudpan189-go > login
请输入用户名(手机号/邮箱/别名), 回车键提交 > ***
请输入密码(输入的密码无回显, 确认输入完成, 回车提交即可) > 
天翼帐号登录成功:   
cloudpan189-go:/  $ 
`

上面是铂金会员，登录失败，下面是黄金会员，登录成功。

**Comment by codecodify** [comment]
下载最新版也是报错，早知道就不升级铂金会员了

**Comment by tickstep** [comment]
> 下载最新版也是报错，早知道就不升级铂金会员了

你帮忙开debug日志，贴上来看看是什么问题。跟会员应该没关系才对

**Comment by codecodify** [comment]
> > 下载最新版也是报错，早知道就不升级铂金会员了
> 
> 你帮忙开debug日志，贴上来看看是什么问题。跟会员应该没关系才对

```shell
请输入用户名(手机号/邮箱/别名), 回车键提交 > 13924755965
请输入密码(输入的密码无回显, 确认输入完成, 回车提交即可) >
[2023-1-30 21:46:50.501] do request url: https://cloud.189.cn/unifyLoginForPC.action?appId=8025431004&clientType=10020&returnURL=https://m.cloud.189.cn/zhuanti/2020/loginErrorPc/index.html&timeStamp=49165061
[2023-1-30 21:46:51.782] do request url: https://open.e.189.cn/api/logbox/oauth2/loginSubmit.do
[2023-1-30 21:46:52.103] response: {
	"result":0,
	"msg":"登录成功",
	"toUrl":"https://m.cloud.189.cn/zhuanti/2020/loginErrorPc/index.html?appId=8025431004&paras=5F2E1D846E7A6384780F24000F1DC68D335D5A271DD47091D8DC35C06F2895D9A2482CF8B5396DDC9EB070E4454B5A307892F6013BA1C163F58B77DAD4024BC7BA51B6BD8F802FAEA5DFA4401A3311E39916120E49C0A948D859EECBC3182E801C1EB61C14DA4F35914B6DE26274C695E2541EFF73C9B69F496426359FFD7B7A1EC7AA53C66BF5E2F393D6248D0C55D1F28C8CCC17652BE807E473056ADCC0AFEE76BB876B6CFB49CF9FC64AF5919332D2A60B7DA12D401ED7B1F1F630FC5C0E85E5D5C7042D2EA1FB74E0F9E51797352CB82196542CDE5AEBF7EADD6D15507E1D089DEEB47DA238F9EB950E29C5F3A303B67FCE7DFB09D6FB8154A70D8B84C582595FE9576B082D63C962F9732653706ADB5CCDAFE9CC2F266623FF31DDC61AD29236E235ABF82F14F7E679922284117509905842FC1352EC91B4CAEB6F2DC7B67A27833921461EF3FAD77667442ADAB13FBED406D0894B4806769BE22BAB5C9F21A9D1267074C40FA0F4585CC53ABF07B0C86C59F1FF80B4EBF660404C8E5B5780EC7CC401A876137F98B70A885149E765358A5AD68E75E6941B772B0F95BB555487C0B24700956613E47C9332EA10EB07980F36A8957C63E87E60B5AF871339FA8BD43960B444F34123E91DC2CC65089B74DECA3D443F&sign=10EB3456A6CB6CE60947F5EC00652E68F07213A6"
}
[2023-1-30 21:46:52.103] do request url: https://api.cloud.189.cn/getSessionForPC.action?clientType=TELEMAC&version=1.0.0&channelId=web_cloud.189.cn&redirectURL=https%3A%2F%2Fm.cloud.189.cn%2Fzhuanti%2F2020%2FloginErrorPc%2Findex.html%3FappId%3D8025431004%26paras%3D5F2E1D846E7A6384780F24000F1DC68D335D5A271DD47091D8DC35C06F2895D9A2482CF8B5396DDC9EB070E4454B5A307892F6013BA1C163F58B77DAD4024BC7BA51B6BD8F802FAEA5DFA4401A3311E39916120E49C0A948D859EECBC3182E801C1EB61C14DA4F35914B6DE26274C695E2541EFF73C9B69F496426359FFD7B7A1EC7AA53C66BF5E2F393D6248D0C55D1F28C8CCC17652BE807E473056ADCC0AFEE76BB876B6CFB49CF9FC64AF5919332D2A60B7DA12D401ED7B1F1F630FC5C0E85E5D5C7042D2EA1FB74E0F9E51797352CB82196542CDE5AEBF7EADD6D15507E1D089DEEB47DA238F9EB950E29C5F3A303B67FCE7DFB09D6FB8154A70D8B84C582595FE9576B082D63C962F9732653706ADB5CCDAFE9CC2F266623FF31DDC61AD29236E235ABF82F14F7E679922284117509905842FC1352EC91B4CAEB6F2DC7B67A27833921461EF3FAD77667442ADAB13FBED406D0894B4806769BE22BAB5C9F21A9D1267074C40FA0F4585CC53ABF07B0C86C59F1FF80B4EBF660404C8E5B5780EC7CC401A876137F98B70A885149E765358A5AD68E75E6941B772B0F95BB555487C0B24700956613E47C9332EA10EB07980F36A8957C63E87E60B5AF871339FA8BD43960B444F34123E91DC2CC65089B74DECA3D443F%26sign%3D10EB3456A6CB6CE60947F5EC00652E68F07213A6
[2023-1-30 21:46:52.775] response: {"res_code": 0, "res_message": "成功","accessToken":"ee6bedb8dfc645aca18be12fdd406fa8","familySessionKey":"465c1997-71ce-4ee2-bf7e-1f31fb3dc188_family","familySessionSecret":"05A2ED1D92DB4C63159FD63760A4A8AC","getFileDiffSpan":60,"getUserInfoSpan":600,"isSaveName":"true","keepAlive":1000,"loginName":"13924755965@189.cn","refreshToken":"2f9652743ca548cb93ad7796e2b0157e","sessionKey":"e4ce2c38-184e-471b-b339-633c9bed0946","sessionSecret":"05A2ED1D92DB4C63159FD63760A4A8AC"}

[2023-1-30 21:46:53.251] response: {"expiresIn":1677728813000,"accessToken":"B7F48748BD6854D70A81845CBB25F8A4"}

[2023-1-30 21:46:53.251] do request url: https://cloud.189.cn/ssoLogin.action?sessionKey=e4ce2c38-184e-471b-b339-633c9bed0946&redirectUrl=main.action%23recycle
[2023-1-30 21:46:54.654] get COOKIE_LOGIN_USER by session key
[2023-1-30 21:46:55.187] get user info failed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x12c pc=0x83ed01a]

goroutine 1 [running]:
github.com/tickstep/cloudpan189-go/internal/command.CmdLogin.func1(0xa4c08f0, 0x0, 0x87bc0a0)
	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/internal/command/login.go:61 +0x2ba
github.com/urfave/cli.HandleAction(0x843da40, 0x84e45c0, 0xa4c08f0, 0xa4c08f0, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0xd0
github.com/urfave/cli.Command.Run(0x84b9a92, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x84c67e5, 0x18, 0x0, ...)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x48f
github.com/urfave/cli.(*App).Run(0xa483180, 0xa40c050, 0x2, 0x2, 0x0, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x673
main.main()
	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/main.go:477 +0xf97
```

报了空指针错误，最开始没有开通会员，不知道为什么现在登录失败了，尝试删掉`cloud189_uploading.json`文件也不行
