### ISSUE TITLE
登陆、获取文件列表等操作频繁报错

### ISSUE THREAD

**Issue by Blackbytes-max** [tickstep/cloudpan189-go#73]
请 输 入 密 码 (输 入 的 密 码 无 回 显 , 确 认 输 入 完 成 , 回 车 提 交 即 可 ) >
panic: runtime error: index out of range [1] with length 0
goroutine 1 [running]:
github.com/tickstep/cloudpan189-api/cloudpan.getLoginParams(0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/tickst
ep/cloudpan189-api@v0.0.9/cloudpan/login.go:151 +0x370
github.com/tickstep/cloudpan189-api/cloudpan.Login(0x2418130, 0xb
, 0x2418150, 0xa, 0x2470000, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/tickst
ep/cloudpan189-api@v0.0.9/cloudpan/login.go:68 +0x80
github.com/tickstep/cloudpan189-go/cmder.DoLoginHelper(0x2418130,
 0xb, 0x2418150, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan1
89-go/cmder/cmder_helper.go:81 +0x1dc
github.com/tickstep/cloudpan189-go/internal/command.RunLogin(0x0,
 0x0, 0x0, 0x0, 0x0, 0xf, 0x2670922, 0x2643550, 0x18eb8, 0x26bee4
0, ...)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan1
89-go/internal/command/login.go:132 +0x4c
github.com/tickstep/cloudpan189-go/internal/command.CmdLogin.func
1(0x25664d0, 0x26da100, 0x787748)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan1
89-go/internal/command/login.go:50 +0xf0
github.com/urfave/cli.HandleAction(0x424fc8, 0x4bfe6c, 0x25664d0,
 0x25664d0, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave
/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0xf0
github.com/urfave/cli.Command.Run(0x49506a, 0x5, 0x0, 0x0, 0x0, 0
x0, 0x0, 0x4a1f5f, 0x18, 0x0, ...)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave
/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x3ec
github.com/urfave/cli.(*App).Run(0x2674e00, 0x250a000, 0x2, 0x2,
0x0, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave
/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x54c
main.main()
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan1
89-go/main.go:477 +0xda0

**Comment by Blackbytes-max** [comment]
设备：nanopi r5s
系统：debian 10 arm64

**Comment by wsyjh** [comment]
一样的报错，ubuntu20.04.5，amd64

**Comment by lanhao34** [comment]
duplicate #54
