### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Antidington** [tickstep/cloudpan189-go#89]
设备是macOS M1芯片，登录过程中报错：
```bash
cloudpan189-go > login -username=xxxxxx@189.cn -password=xxxxxxxx
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x230 pc=0x101177c90]

goroutine 1 [running]:
github.com/tickstep/cloudpan189-go/internal/command.CmdLogin.func1(0x140001e0160)
	github.com/tickstep/cloudpan189-go/internal/command/login.go:61 +0x220
github.com/urfave/cli.HandleAction({0x101291160?, 0x10132bf28?}, 0x5?)
	github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0x58
github.com/urfave/cli.Command.Run({{0x101188fa5, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x10119647e, 0x18}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x554
github.com/urfave/cli.(*App).Run(0x14000206380, {0x1400032c040, 0x4, 0x4})
	github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x838
main.main.func1(0x140001e06e0)
	github.com/tickstep/cloudpan189-go/main.go:356 +0x654
github.com/urfave/cli.HandleAction({0x101288b60?, 0x1400039d730?}, 0x1400010a200?)
	github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:525 +0x94
github.com/urfave/cli.(*App).Run(0x14000206380, {0x1400010a200, 0x1, 0x1})
	github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:285 +0x5b0
main.main()
	github.com/tickstep/cloudpan189-go/main.go:547 +0x1558
```

**Comment by BugTan** [comment]
same issue
