### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by han-jingyu** [tickstep/cloudpan189-go#90]
报错:

天翼帐号登录成功:  *****
ERROR: panic: runtime error: invalid memory address or nil pointer dereference
ERROR: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x856e8b]
ERROR: 
ERROR: goroutine 53 [running]:
ERROR: [github.com/tickstep/cloudpan189-go/internal/functions/panupload](http://github.com/tickstep/cloudpan189-go/internal/functions/panupload).(*boltDB).Next(0xc0001e00f0, 0xc00047ed38, 0x14, 0x0, 0x0, 0x0)
ERROR: 	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/internal/functions/panupload/sync_database_bolt.go:149 +0x30b
ERROR: [github.com/tickstep/cloudpan189-go/internal/functions/panupload](http://github.com/tickstep/cloudpan189-go/internal/functions/panupload).(*boltDB).clean(0xc0001e00f0, 0xc8)
ERROR: 	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/internal/functions/panupload/sync_database_bolt.go:89 +0x6f
ERROR: [github.com/tickstep/cloudpan189-go/internal/functions/panupload](http://github.com/tickstep/cloudpan189-go/internal/functions/panupload).(*boltDB).Close(0xc0001e00f0, 0x14, 0xc00047ed50)
ERROR: 	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/internal/functions/panupload/sync_database_bolt.go:179 +0x73
ERROR: [github.com/tickstep/cloudpan189-go/internal/command.DelRemoteFileFromDB](http://github.com/tickstep/cloudpan189-go/internal/command.DelRemoteFileFromDB)(0x0, 0x7ffea739ceae, 0x14, 0xc00047ed38, 0x14, 0x1)
ERROR: 	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/internal/command/backup.go:242 +0x5a7
ERROR: [github.com/tickstep/cloudpan189-go/internal/command.Backup.func1](http://github.com/tickstep/cloudpan189-go/internal/command.Backup.func1)(0xc00050fbb0, 0x101, 0xc000320f40, 0x7ffea739cec3, 0xa, 0xc00037c900, 0x7ffea739ceae, 0x14)
ERROR: 	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/internal/command/backup.go:309 +0x1fa
ERROR: created by [github.com/tickstep/cloudpan189-go/internal/command.Backup](http://github.com/tickstep/cloudpan189-go/internal/command.Backup)
ERROR: 	/Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/internal/command/backup.go:303 +0x4ca
APP登录失败： invalid character '<' looking for beginning of value
退出用户成功: *****

Debian linux, amd64 系统

**Comment by toss-a** [comment]
同样问题
